import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { LineItem } from "../../types/wooCommerce.types";

interface CartItem {
  productId: number;
  quantity: number;
}
// Define a type for the slice state
interface CartState {
  lineItems: Record<string, CartItem>;
}

// Define the initial state using that type
const initialState: CartState = {
  lineItems: {},
};

// NOTE: Redux Toolkit's createReducer API uses Immer internally automatically making it safe to mutate state. createSlice uses createReducer inside so it's also safe to mutate state there as well. This even applies if the case reducer functions are defined outside of the createSlice/createReducer call (as in the functions defined below)
const addLineItemReducer = (
  state: CartState,
  action: PayloadAction<CartItem>
) => {
  console.log({action});
  
  const productId = action.payload.productId;
  const lineItem = state.lineItems[productId] || (<CartItem>{
    productId,
    quantity: 0
  });
  state.lineItems = {
    ...state.lineItems,
    [productId]: {
      ...lineItem,
      quantity: lineItem.quantity + action.payload.quantity
    }
    }
};

const decrementQuantityReducer = (
  state: CartState,
  action: PayloadAction<CartItem>
) => {
  const lineItem = state.lineItems[action.payload.productId];
  if(!lineItem) {
    delete state.lineItems[action.payload.productId];
  } else {
    state.lineItems = {
      ...state.lineItems,
      [lineItem.productId]: {
        ...lineItem,
        quantity: lineItem.quantity - 1
      }
      }
  }
};

const removeLineItemReducer = (
  state: CartState,
  action: PayloadAction<CartItem>
) => {
  const lineItem = state.lineItems[action.payload.productId];
  if(!lineItem) {
    delete state.lineItems[action.payload.productId];
  }
};

export const cartSlice = createSlice({
  name: "cart",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  // Use the PayloadAction type to declare the contents of `action.payload`
  reducers: {
    addLineItem: addLineItemReducer,
    decrementLineItemQuantity: decrementQuantityReducer,
    removeLineItem: removeLineItemReducer,
    resetCartState() {
      return initialState;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: (builder) => {}
});

// reducers/actions go in here in order to import them into components
export const {
  addLineItem,
  decrementLineItemQuantity,
  removeLineItem,
  resetCartState,
} = cartSlice.actions;

export default cartSlice.reducer;